import 'package:drift/drift.dart';

// ---------------------------------------------------------------------------
// Every table in the app lives here, declared once by the foundation slice.
//
// Feature slices do NOT add tables and do NOT edit this file. A feature reads
// and writes its own rows from its own local datasource with plain Drift
// queries (`db.select(db.medications)`), which is why no per-feature DAO is
// registered on AppDatabase either. One owner for the schema means five
// people never collide in a generated file.
//
// Shape rules, uniform across every user-generated log table:
//
//  * `clientRecordId` is the primary key and is a UUID generated on the
//    device at the moment of capture. It is also the server's idempotency key
//    (`UNIQUE (user_id, client_record_id)`), which is what makes replaying the
//    sync queue safe.
//  * `serverId` is null until the record has been accepted by the server.
//  * Fields the UI filters or sorts on get real columns; everything else
//    rides along as JSON, mirroring the backend's own JSONB columns.
//  * Logs are append-only. The backend treats them as immutable clinical
//    history and never overwrites, so neither do we.
// ---------------------------------------------------------------------------

/// The signed-in user, cached so the app can open to a greeting with no
/// network. Exactly one row is ever present.
class CachedUsers extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  TextColumn get phone => text()();
  TextColumn get preferredLanguage => text()();
  TextColumn get role => text()();

  @override
  Set<Column<Object>> get primaryKey => <Column<Object>>{id};
}

/// Small key/value store for device-local settings. The language choice lives
/// here because it is device state, not a secret and not server-owned.
class Preferences extends Table {
  TextColumn get key => text()();
  TextColumn get value => text()();

  @override
  Set<Column<Object>> get primaryKey => <Column<Object>>{key};
}

abstract final class PreferenceKeys {
  static const String language = 'language';
  static const String languageChosen = 'language_chosen';

  /// Owned by M2 (settings), read by M3 (reminders).
  static const String notificationsEnabled = 'notifications_enabled';
  static const String symptomPromptTime = 'symptom_prompt_time';

  /// Owned by the sync engine.
  static const String lastSyncAt = 'last_sync_at';
}

/// The patient's own profile — one row, keyed by user id.
///
/// Mirrors `GET/PUT /api/v1/patients/me`. Remember that the PUT is a full
/// replace, so this row must always hold the complete profile, never a patch.
class PatientProfiles extends Table {
  TextColumn get userId => text()();

  /// Year only, by scope decision — never a full date of birth.
  IntColumn get birthYear => integer().nullable()();
  TextColumn get preferredLanguage => text().nullable()();
  RealColumn get heightCm => real().nullable()();
  TextColumn get chdStage => text().nullable()();
  TextColumn get diseaseHistory => text().nullable()();

  /// JSON array of strings.
  TextColumn get comorbiditiesJson =>
      text().withDefault(const Constant('[]'))();
  TextColumn get managementPlan => text().nullable()();

  /// JSON object: bpSystolic, bpDiastolic, totalCholesterol, stepsPerDay,
  /// targetWeightKg, dietNote.
  TextColumn get goalsJson => text().nullable()();

  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => <Column<Object>>{userId};
}

/// A medication the patient is taking. Unlike the log tables this one is
/// mutable — it can be edited and soft-deactivated.
class Medications extends Table {
  TextColumn get clientRecordId => text()();
  TextColumn get serverId => text().nullable()();
  TextColumn get name => text().withLength(max: 255)();
  RealColumn get doseMg => real()();

  /// ONCE_DAILY | BID | TID | CUSTOM
  TextColumn get frequency => text()();

  /// JSON array of "HH:mm" strings.
  TextColumn get scheduleTimesJson => text()();
  BoolColumn get active => boolean().withDefault(const Constant(true))();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => <Column<Object>>{clientRecordId};
}

/// One logged dose. Append-only.
class DoseLogs extends Table {
  TextColumn get clientRecordId => text()();
  TextColumn get serverId => text().nullable()();

  /// Always set. The sync payload sends `medicationClientRecordId` when the
  /// medication itself has not reached the server yet, which is why the local
  /// link is by client id rather than server id.
  TextColumn get medicationClientRecordId => text()();
  TextColumn get medicationServerId => text().nullable()();

  /// TAKEN | MISSED | SKIPPED
  TextColumn get status => text()();

  /// yyyy-MM-dd, the day the dose was due.
  TextColumn get scheduledDate => text()();

  /// HH:mm, nullable for an unscheduled dose.
  TextColumn get scheduledTime => text().nullable()();
  DateTimeColumn get loggedAt => dateTime()();
  TextColumn get note => text().withLength(max: 500).nullable()();

  @override
  Set<Column<Object>> get primaryKey => <Column<Object>>{clientRecordId};
}

/// A vitals reading. Append-only.
class VitalsLogs extends Table {
  TextColumn get clientRecordId => text()();
  TextColumn get serverId => text().nullable()();

  /// BLOOD_PRESSURE | GLUCOSE | HEART_RATE | WEIGHT | CHOLESTEROL
  TextColumn get type => text()();

  /// JSON object whose keys depend on `type` — exactly the required keys for
  /// that type, no more.
  TextColumn get valuesJson => text()();

  /// Authoritative only once the server has answered; computed locally by
  /// `core/clinical` in the meantime so an offline entry still shows a status.
  BoolColumn get flagged => boolean().nullable()();

  /// Server-computed snapshot on a WEIGHT entry when profile height is known.
  RealColumn get bmi => real().nullable()();
  DateTimeColumn get measuredAt => dateTime()();
  TextColumn get note => text().withLength(max: 500).nullable()();

  @override
  Set<Column<Object>> get primaryKey => <Column<Object>>{clientRecordId};
}

/// A daily symptom check-in. Append-only.
class SymptomLogs extends Table {
  TextColumn get clientRecordId => text()();
  TextColumn get serverId => text().nullable()();

  /// JSON object, strictly whitelisted by the server: chestPain,
  /// shortnessOfBreath, heartRate, bloodPressure, swelling, energyLevel,
  /// worseThanYesterday.
  TextColumn get dataJson => text()();

  /// Server-computed `{overall, symptoms{}}`. Null until synced; the local
  /// evaluator fills the gap for offline entries.
  TextColumn get assessmentJson => text().nullable()();

  /// NONE | MONITOR | URGENT | EMERGENCY — denormalised out of the assessment
  /// so history lists can sort and filter without parsing JSON.
  TextColumn get overallSeverity => text().nullable()();
  DateTimeColumn get measuredAt => dateTime()();
  TextColumn get note => text().withLength(max: 500).nullable()();

  @override
  Set<Column<Object>> get primaryKey => <Column<Object>>{clientRecordId};
}

/// A physical-activity session. Append-only. The server computes nothing here.
class ActivityLogs extends Table {
  TextColumn get clientRecordId => text()();
  TextColumn get serverId => text().nullable()();

  /// WALKING | JOGGING | CYCLING | HOUSEHOLD | FARMING | STRETCHING | OTHER
  TextColumn get type => text()();
  IntColumn get durationMinutes => integer()();

  /// LIGHT | MODERATE | VIGOROUS
  TextColumn get intensity => text()();
  IntColumn get steps => integer().nullable()();
  RealColumn get distanceMeters => real().nullable()();
  DateTimeColumn get measuredAt => dateTime()();
  TextColumn get note => text().withLength(max: 500).nullable()();

  @override
  Set<Column<Object>> get primaryKey => <Column<Object>>{clientRecordId};
}

/// What this device still owes the server.
///
/// This is the device-side queue described in `ARCHITECTURE.md` section 7.2.
/// It is deliberately self-contained: it carries the whole outbound payload,
/// so the sync engine never has to know the shape of any feature table. That
/// is what lets one person own sync while five people own the features.
class SyncQueueEntries extends Table {
  IntColumn get id => integer().autoIncrement()();

  /// The idempotency key. Matches the `clientRecordId` of the row in the
  /// feature table this entry was created from.
  TextColumn get clientRecordId => text()();
  TextColumn get entityType => text()();

  /// The feature's normal request body, JSON-encoded, ready to post as-is.
  TextColumn get payloadJson => text()();
  TextColumn get status => textEnum<LocalSyncStatus>()();

  /// Written back from the sync response. Features read it from here rather
  /// than the engine writing into feature tables — a read-side join keeps the
  /// engine ignorant of every feature's schema.
  TextColumn get serverId => text().nullable()();
  IntColumn get attempts => integer().withDefault(const Constant(0))();
  TextColumn get lastError => text().nullable()();

  /// When the user actually captured the record — the value that matters
  /// clinically, and the order the queue drains in.
  DateTimeColumn get recordedAt => dateTime()();
  DateTimeColumn get createdLocallyAt => dateTime()();

  @override
  List<String> get customConstraints => <String>[
    'UNIQUE (entity_type, client_record_id)',
  ];
}

/// Local lifecycle of a queued record.
///
/// The server's four outcomes collapse onto this: `SAVED` and `DUPLICATE` both
/// become [synced]; `CONFLICT` becomes [conflict], which is also terminal
/// because the stored record always wins and the incoming one is never
/// written; `REJECTED` becomes [rejected] and must never be retried.
enum LocalSyncStatus { pending, syncing, synced, conflict, rejected }

/// `entityType` values the sync endpoint accepts, with their exact wire
/// spelling. Stored as plain text rather than a Drift `textEnum` because the
/// wire form is SCREAMING_SNAKE and an enum's `.name` is not.
enum SyncEntityType {
  vital('VITAL'),
  symptom('SYMPTOM'),
  activity('ACTIVITY'),
  medication('MEDICATION'),
  doseLog('DOSE_LOG');

  const SyncEntityType(this.wire);

  final String wire;

  static SyncEntityType fromWire(String value) =>
      values.firstWhere((SyncEntityType e) => e.wire == value);
}
